version: "3"

services:
  pg:
    image: postgres:16.1-bullseye
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: rust_htmx
    ports:
      - "5469:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
