version: "3"

tasks:
  start:dev:
    desc: start with server in dev mod with watch
    cmds:
      - cargo run
    sources:
      - ./src/**/*.*
      - ./templates/**/*.{html,scss}
    deps:
      - task: styles
      - task: start:db
      - task: prisma:gen

  start:db:
    desc: start database
    cmds:
      - docker compose up -d

  styles:
    desc: tailwindcss build with watch
    cmds:
      - npm exec -- tailwindcss --minify -i ./templates/index.scss -o ./assets/css/main.min.css
    sources:
      - ./templates/**/*.{html,scss}
    deps:
      - task: npm:install

  prisma:gen:
    desc: generate prisma client
    cmds:
      - cargo prisma generate
    sources:
      - ./prisma/schema.prisma

  npm:install:
    desc: install npm dependencies
    cmds:
      - npm i
    sources:
      - ./package.json
